package edu.alibaba.mpc4j.s2pc.upso.upsu.sogs.unbalanced;

import edu.alibaba.mpc4j.common.rpc.MpcAbortException;
import edu.alibaba.mpc4j.common.rpc.pto.AbstractTwoPartyMemoryRpcPto;
import org.junit.Assert;
import org.junit.Assume;
import org.junit.Test;

import java.util.Arrays;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Random;
import java.util.Set;

/**
 * Tests for loading native ePSU / pnMCRG pad-carrier files into the Java SOGS release path.
 *
 * @author donghai hou
 * @date 2026/06/17
 */
public class EpsuPnmcrgPadCarrierFileLoaderTest extends AbstractTwoPartyMemoryRpcPto {
    /**
     * Sender size.
     */
    private static final int M = 64;
    /**
     * Padded rows.
     */
    private static final int ROW_NUM = 128;
    /**
     * Payload byte length matching one native block.
     */
    private static final int PAYLOAD_BYTE_LENGTH = 16;
    /**
     * Pad byte length matching one native block.
     */
    private static final int PAD_BYTE_LENGTH = 16;
    /**
     * SOGS cells.
     */
    private static final int CELL_NUM = 512;
    /**
     * SOGS degree.
     */
    private static final int DEGREE = 3;
    /**
     * Test alpha max cache count.
     */
    private static final long ALPHA_MAX_CACHE_COUNT = 7L;
    /**
     * Native smoke sender pad file generated by ePSU / pnMCRG.
     */
    private static final Path NATIVE_SENDER_FILE = Path.of(
        "/Users/haydnhou/Desktop/ePSU-main/unbalanced_ePSU/MCRG/build/padCarrier/sender_pad_carrier"
    );
    /**
     * Native smoke receiver pad file generated by ePSU / pnMCRG.
     */
    private static final Path NATIVE_RECEIVER_FILE = Path.of(
        "/Users/haydnhou/Desktop/ePSU-main/unbalanced_ePSU/MCRG/build/padCarrier/receiver_pad_carrier"
    );
    /**
     * Native smoke SOGS cells.
     */
    private static final int NATIVE_CELL_NUM = 4096;

    public EpsuPnmcrgPadCarrierFileLoaderTest() {
        super(EpsuPnmcrgPadCarrierFileLoaderTest.class.getSimpleName());
    }

    @Test
    public void testLoadNativeFilesThenRelease() throws Exception {
        CaseData data = createCase();
        Path dir = Files.createTempDirectory("epsu-pad-carrier-loader");
        Path senderFilePath = dir.resolve("sender_pad_carrier");
        Path receiverFilePath = dir.resolve("receiver_pad_carrier");
        writeSenderFile(senderFilePath, data.carrier.getSenderOutput());
        writeReceiverFile(receiverFilePath, data.carrier.getReceiverOutput());

        EpsuPnmcrgPadCarrierFileLoader.SenderFile senderFile =
            EpsuPnmcrgPadCarrierFileLoader.loadSender(senderFilePath);
        EpsuPnmcrgPadCarrierFileLoader.ReceiverFile receiverFile =
            EpsuPnmcrgPadCarrierFileLoader.loadReceiver(receiverFilePath);
        EpsuPnmcrgPadCarrierFileLoader.checkCompatible(senderFile, receiverFile);

        Assert.assertEquals(ROW_NUM, senderFile.getRowNum());
        Assert.assertEquals(ROW_NUM, receiverFile.getRowNum());
        Assert.assertEquals(ALPHA_MAX_CACHE_COUNT, senderFile.getAlphaMaxCacheCount());
        Assert.assertEquals(ALPHA_MAX_CACHE_COUNT, receiverFile.getAlphaMaxCacheCount());
        Assert.assertEquals(PAD_BYTE_LENGTH, senderFile.getPadByteLength());
        Assert.assertEquals(PAD_BYTE_LENGTH, receiverFile.getPadByteLength());
        Assert.assertEquals(PAYLOAD_BYTE_LENGTH, senderFile.getPayloadByteLength());

        runRelease(senderFile.getOutput(), receiverFile.getOutput(), data.expectedMisses);
    }

    @Test
    public void testLoadNativeSmokeFilesThenRelease() throws Exception {
        Assume.assumeTrue(Files.exists(NATIVE_SENDER_FILE));
        Assume.assumeTrue(Files.exists(NATIVE_RECEIVER_FILE));
        EpsuPnmcrgPadCarrierFileLoader.SenderFile senderFile =
            EpsuPnmcrgPadCarrierFileLoader.loadSender(NATIVE_SENDER_FILE);
        EpsuPnmcrgPadCarrierFileLoader.ReceiverFile receiverFile =
            EpsuPnmcrgPadCarrierFileLoader.loadReceiver(NATIVE_RECEIVER_FILE);
        EpsuPnmcrgPadCarrierFileLoader.checkCompatible(senderFile, receiverFile);

        Set<ByteBuffer> expectedMisses = expectedNativeMisses(
            senderFile.getOutput(), receiverFile.getOutput()
        );
        Assert.assertFalse(expectedMisses.isEmpty());
        runRelease(
            senderFile.getOutput(),
            receiverFile.getOutput(),
            expectedMisses,
            senderFile.getPayloadByteLength(),
            NATIVE_CELL_NUM
        );
    }

    private void runRelease(
        McrgTokenSogsPadCarrierSenderOutput senderOutput,
        McrgTokenSogsPadCarrierReceiverOutput receiverOutput,
        Set<ByteBuffer> expectedMisses
    ) throws Exception {
        runRelease(senderOutput, receiverOutput, expectedMisses, PAYLOAD_BYTE_LENGTH, CELL_NUM);
    }

    private void runRelease(
        McrgTokenSogsPadCarrierSenderOutput senderOutput,
        McrgTokenSogsPadCarrierReceiverOutput receiverOutput,
        Set<ByteBuffer> expectedMisses,
        int payloadByteLength,
        int cellNum
    ) throws Exception {
        McrgTokenSogsReleaseConfig config = new McrgTokenSogsReleaseConfig.Builder().build();
        McrgTokenSogsReleaseSender sender =
            new McrgTokenSogsReleaseSender(firstRpc, secondRpc.ownParty(), config);
        McrgTokenSogsReleaseReceiver receiver =
            new McrgTokenSogsReleaseReceiver(secondRpc, firstRpc.ownParty(), config);
        int taskId = Math.abs(SECURE_RANDOM.nextInt());
        sender.setTaskId(taskId);
        receiver.setTaskId(taskId);
        sender.init();
        receiver.init();
        firstRpc.reset();
        secondRpc.reset();

        SenderThread senderThread = new SenderThread(sender, senderOutput);
        ReceiverThread receiverThread = new ReceiverThread(receiver, receiverOutput, payloadByteLength, cellNum);
        senderThread.start();
        receiverThread.start();
        senderThread.join();
        receiverThread.join();
        senderThread.check();
        receiverThread.check();

        Assert.assertTrue(receiverThread.peelResult.success);
        Assert.assertEquals(0, receiverThread.peelResult.residualCells);
        Assert.assertEquals(expectedMisses, receiverThread.peelResult.recovered);

        new Thread(sender::destroy).start();
        new Thread(receiver::destroy).start();
    }

    private static Set<ByteBuffer> expectedNativeMisses(
        McrgTokenSogsPadCarrierSenderOutput senderOutput,
        McrgTokenSogsPadCarrierReceiverOutput receiverOutput
    ) {
        byte[][] uPads = senderOutput.getUPads();
        byte[][] vPads = receiverOutput.getVPads();
        boolean[] realRowBits = senderOutput.getRealRowBits();
        byte[][] payloads = senderOutput.getPayloads();
        Set<ByteBuffer> expectedMisses = new HashSet<>();
        for (int row = 0; row < senderOutput.getRowNum(); row++) {
            if (realRowBits[row] && Arrays.equals(uPads[row], vPads[row])) {
                expectedMisses.add(ByteBuffer.wrap(Arrays.copyOf(payloads[row], payloads[row].length)));
            }
        }
        return expectedMisses;
    }

    private static CaseData createCase() {
        Random random = new Random(2026061706L);
        List<Integer> rowIndexes = new ArrayList<>(ROW_NUM);
        for (int i = 0; i < ROW_NUM; i++) {
            rowIndexes.add(i);
        }
        Collections.shuffle(rowIndexes, random);
        List<Integer> realRows = rowIndexes.subList(0, M);
        Set<Integer> hitRows = new HashSet<>(realRows.subList(0, M / 2));
        byte[][] uPads = new byte[ROW_NUM][PAD_BYTE_LENGTH];
        byte[][] vPads = new byte[ROW_NUM][PAD_BYTE_LENGTH];
        byte[][] payloads = new byte[ROW_NUM][PAYLOAD_BYTE_LENGTH];
        boolean[] realRowBits = new boolean[ROW_NUM];
        boolean[] openRowBits = new boolean[ROW_NUM];
        for (int row = 0; row < ROW_NUM; row++) {
            random.nextBytes(uPads[row]);
            random.nextBytes(vPads[row]);
            payloads[row] = payload(row);
        }
        for (int itemIndex = 0; itemIndex < M; itemIndex++) {
            int row = realRows.get(itemIndex);
            payloads[row] = payload(ROW_NUM + itemIndex);
            realRowBits[row] = true;
            openRowBits[row] = !hitRows.contains(row);
        }
        SimulatedMcrgTokenSogsPadCarrier carrier =
            SimulatedMcrgTokenSogsPadCarrier.create(uPads, vPads, realRowBits, openRowBits, payloads);
        return new CaseData(carrier, carrier.getExpectedMisses());
    }

    private static void writeSenderFile(
        Path path, McrgTokenSogsPadCarrierSenderOutput senderOutput
    ) throws Exception {
        byte[][] uPads = senderOutput.getUPads();
        boolean[] realRowBits = senderOutput.getRealRowBits();
        byte[][] payloads = senderOutput.getPayloads();
        int rowNum = senderOutput.getRowNum();
        int padByteLength = senderOutput.getPadByteLength();
        int payloadByteLength = senderOutput.getPayloadByteLength();
        ByteBuffer buffer = ByteBuffer.allocate(
            Long.BYTES * 4 + rowNum * padByteLength + rowNum + rowNum * payloadByteLength
        ).order(ByteOrder.LITTLE_ENDIAN);
        buffer.putLong(rowNum);
        buffer.putLong(ALPHA_MAX_CACHE_COUNT);
        buffer.putLong(padByteLength);
        buffer.putLong(payloadByteLength);
        for (byte[] uPad : uPads) {
            buffer.put(uPad);
        }
        for (boolean realRowBit : realRowBits) {
            buffer.put((byte) (realRowBit ? 1 : 0));
        }
        for (byte[] payload : payloads) {
            buffer.put(payload);
        }
        Files.write(path, buffer.array());
    }

    private static void writeReceiverFile(
        Path path, McrgTokenSogsPadCarrierReceiverOutput receiverOutput
    ) throws Exception {
        byte[][] vPads = receiverOutput.getVPads();
        int rowNum = receiverOutput.getRowNum();
        int padByteLength = receiverOutput.getPadByteLength();
        ByteBuffer buffer = ByteBuffer.allocate(
            Long.BYTES * 3 + rowNum * padByteLength
        ).order(ByteOrder.LITTLE_ENDIAN);
        buffer.putLong(rowNum);
        buffer.putLong(ALPHA_MAX_CACHE_COUNT);
        buffer.putLong(padByteLength);
        for (byte[] vPad : vPads) {
            buffer.put(vPad);
        }
        Files.write(path, buffer.array());
    }

    private static byte[] payload(int itemIndex) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            digest.update("epsu-pad-carrier-loader".getBytes(StandardCharsets.UTF_8));
            digest.update(ByteBuffer.allocate(Integer.BYTES).putInt(itemIndex).array());
            byte[] hash = digest.digest();
            byte[] payload = new byte[PAYLOAD_BYTE_LENGTH];
            System.arraycopy(hash, 0, payload, 0, payload.length);
            return payload;
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException(e);
        }
    }

    private static class SenderThread extends Thread {
        private final McrgTokenSogsReleaseSender sender;
        private final McrgTokenSogsPadCarrierSenderOutput senderOutput;
        private Exception exception;

        private SenderThread(
            McrgTokenSogsReleaseSender sender, McrgTokenSogsPadCarrierSenderOutput senderOutput
        ) {
            this.sender = sender;
            this.senderOutput = senderOutput;
        }

        @Override
        public void run() {
            try {
                sender.send(senderOutput);
            } catch (MpcAbortException e) {
                exception = e;
            }
        }

        private void check() throws Exception {
            if (exception != null) {
                throw exception;
            }
        }
    }

    private static class ReceiverThread extends Thread {
        private final McrgTokenSogsReleaseReceiver receiver;
        private final McrgTokenSogsPadCarrierReceiverOutput receiverOutput;
        private final int payloadByteLength;
        private final int cellNum;
        private TokenKeyedSogsSketch.PeelResult peelResult;
        private Exception exception;

        private ReceiverThread(
            McrgTokenSogsReleaseReceiver receiver,
            McrgTokenSogsPadCarrierReceiverOutput receiverOutput,
            int payloadByteLength,
            int cellNum
        ) {
            this.receiver = receiver;
            this.receiverOutput = receiverOutput;
            this.payloadByteLength = payloadByteLength;
            this.cellNum = cellNum;
        }

        @Override
        public void run() {
            try {
                peelResult = receiver.receive(receiverOutput, payloadByteLength, cellNum, DEGREE);
            } catch (MpcAbortException e) {
                exception = e;
            }
        }

        private void check() throws Exception {
            if (exception != null) {
                throw exception;
            }
        }
    }

    private static class CaseData {
        private final SimulatedMcrgTokenSogsPadCarrier carrier;
        private final Set<ByteBuffer> expectedMisses;

        private CaseData(SimulatedMcrgTokenSogsPadCarrier carrier, Set<ByteBuffer> expectedMisses) {
            this.carrier = carrier;
            this.expectedMisses = expectedMisses;
        }
    }
}
